<a href="https://colab.research.google.com/github/izabellaradichi/programaria_dados/blob/main/estatistica_basica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import numpy as np
import pandas as pd

In [60]:
lista_idades = [26,30,32,22,26,35,40,20,43,31,23]

In [61]:
np.sum(lista_idades) # para exibir só o número, usa-se int(np.sum(lista_idades))

np.int64(328)

In [62]:
len(lista_idades) # quantidade de idades

11

In [63]:
np.sum(lista_idades)/len(lista_idades) # média das idades

np.float64(29.818181818181817)

In [64]:
media = np.mean(lista_idades) # exibição do valor da média
print("Média aritmética:", media)

Média aritmética: 29.818181818181817

In [65]:
lista_idades.sort() # ordena a lista
lista_idades

[20, 22, 23, 26, 26, 30, 31, 32, 35, 40, 43]

In [66]:
lista_idades = [26,30,32,22,26,35,40,20,43,31,23,100]

In [67]:
lista_idades.sort() # ordena a lista
lista_idades

[20, 22, 23, 26, 26, 30, 31, 32, 35, 40, 43, 100]

In [68]:
mediana = np.median(lista_idades) # valor da mediana
print("Mediana:", mediana)

Mediana: 30.5

### Voltando para a tabela

In [69]:
from google.colab import drive

In [70]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [71]:
dados = pd.read_excel('/content/drive/MyDrive/Curso PrograMaria Dados/planilha_modulo3.xlsx')

In [72]:
dados['IDADE'].mean() # média dos valore da coluna IDADE

np.float64(31.169168453657374)

In [73]:
dados['IDADE'].median() # mediana dos valore da coluna IDADE

30.0

In [74]:
dados['IDADE'].mode() # valor que mais aparece na coluna IDADE

0    27.0
Name: IDADE, dtype: float64

In [75]:
dados['IDADE'].std()

6.902802832143141

In [76]:
dados['IDADE'].min() # valor mínimo da coluna

18.0

In [77]:
dados['IDADE'].max() # valor maximo da coluna

54.0

In [78]:
dados[dados['GENERO']=='Feminino']['IDADE'].mean() # média de idade das pessoas do gênero feminino

np.float64(31.318051575931232)

In [79]:
dados[dados['GENERO']=='Masculino']['IDADE'].mean() # média de idade das pessoas do gênero masculino

np.float64(31.147876077930373)

In [80]:
dados[dados['GENERO']=='Feminino']['SALARIO'].mean()

np.float64(8673.22460496614)

In [81]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4271 entries, 0 to 4270
Data columns (total 28 columns):
 #   Column                                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                                     --------------  -----
 0   Unnamed: 0                                                                                                                 4271 non-null   int64
 1   ID                                                                                                                         4271 non-null   object
 2   IDADE                                                                                                                      4197 non-null   float64
 3   FAIXA IDADE                                                                                                                4271 non-null   object
 4   GENERO                                                                                                                     4262 non-null   object
 5   COR/RACA/ETNIA                                                                                                             4271 non-null   object
 6   PCD                                                                                                                        4271 non-null   object
 7   EXPERIENCIA_PROFISSIONAL_PREJUDICADA                                                                                       2190 non-null   object
 8   ASPECTOS_PREJUDICADOS                                                                                                      837 non-null    object
 9   VIVE_NO_BRASIL                                                                                                             4271 non-null   bool
 10  ESTADO ONDE MORA                                                                                                           4156 non-null   object
 11  UF ONDE MORA                                                                                                               4156 non-null   object
 12  REGIAO ONDE MORA                                                                                                           4171 non-null   object
 13  MUDOU DE ESTADO?                                                                                                           4171 non-null   float64
 14  REGIAO DE ORIGEM                                                                                                           772 non-null    object
 15  NIVEL DE ENSINO                                                                                                            4271 non-null   object
 16  ÁREA DE FORMAÇÃO                                                                                                           4149 non-null   object
 17  QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?                                                                                       4271 non-null   object
 18  SETOR                                                                                                                      3694 non-null   object
 19  NUMERO DE FUNCIONARIOS                                                                                                     3694 non-null   object
 20  GESTOR?                                                                                                                    3694 non-null   float64
 21  CARGO COMO GESTOR                                                                                                          713 non-null    object
 22  CARGO ATUAL                                                                                                                2981 non-null   object
 23  NIVEL                                                                                                                      2981 non-null   object
 24  FAIXA SALARIAL                                                                                                             3694 non-null   object
 25  QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?                                                                     3694 non-null   object
 26  QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?  3694 non-null   object
 27  SALARIO                                                                                                                    3694 non-null   float64
dtypes: bool(1), float64(4), int64(1), object(22)
memory usage: 905.2+ KB

### Trabalhando coluna de gênero

In [82]:
dados.groupby('GENERO', dropna=False)['ID'].nunique()

GENERO
Feminino                1055
Masculino               3194
Prefiro não informar      12
NaN                        9
Name: ID, dtype: int64

In [83]:
dados['GENERO'] = dados['GENERO'].fillna("Prefiro não informar") # substitui os NaN por Prefiro não informar

In [84]:
dados.groupby('GENERO', dropna=False)['ID'].nunique() # conferir que substituiu por Prefiro não informar

GENERO
Feminino                1055
Masculino               3194
Prefiro não informar      21
Name: ID, dtype: int64

### Tratando coluna de idade

In [85]:
dados['IDADE'].isnull().value_counts()

IDADE
False    4197
True       74
Name: count, dtype: int64

In [86]:
dados.columns

Index(['Unnamed: 0', 'ID', 'IDADE', 'FAIXA IDADE', 'GENERO', 'COR/RACA/ETNIA',
       'PCD', 'EXPERIENCIA_PROFISSIONAL_PREJUDICADA', 'ASPECTOS_PREJUDICADOS',
       'VIVE_NO_BRASIL', 'ESTADO ONDE MORA', 'UF ONDE MORA',
       'REGIAO ONDE MORA', 'MUDOU DE ESTADO?', 'REGIAO DE ORIGEM',
       'NIVEL DE ENSINO', 'ÁREA DE FORMAÇÃO',
       'QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?', 'SETOR',
       'NUMERO DE FUNCIONARIOS', 'GESTOR?', 'CARGO COMO GESTOR', 'CARGO ATUAL',
       'NIVEL', 'FAIXA SALARIAL',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?',
       'SALARIO'],
      dtype='object')

In [87]:
dados[dados['IDADE'].isnull()]['FAIXA IDADE'].value_counts() # conta a quantidade de null da coluna FAIXA IDADE

FAIXA IDADE
55+      68
17-21     6
Name: count, dtype: int64

In [88]:
media_17_21 = dados[dados['FAIXA IDADE']=='17-21']['IDADE'].mean()
media_17_21

np.float64(20.205479452054796)

In [89]:
dados.loc[(dados['FAIXA IDADE']=='17-21') & (dados['IDADE'].isnull()), 'IDADE'] = media_17_21 # substitui os valores null da coluna FAIXA IDADE pela variavel media_17_21 (20.20)

In [90]:
dados[dados['IDADE'].isnull()]['FAIXA IDADE'].value_counts() # conta quantos valores null tem preenchidos na coluna IDADE e compara com a coluna FAIXA IDADE (e comprova que não tem mais nenhum null na faixa 17-21)

FAIXA IDADE
55+    68
Name: count, dtype: int64

In [91]:
dados[dados['FAIXA IDADE']=='55+']['IDADE'] # consultar os valores da coluna IDADE que preencheram a coluna FAIXA IDADE com o valor 55+

9      NaN
66     NaN
96     NaN
121    NaN
156    NaN
        ..
4001   NaN
4043   NaN
4048   NaN
4061   NaN
4215   NaN
Name: IDADE, Length: 68, dtype: float64

In [92]:
dados[dados['FAIXA IDADE']=='55+']['NIVEL'] # consultar os valores da coluna NIVEL que preencheram a coluna FAIXA IDADE com o valor 55+

9        Pleno
66      Júnior
96       Pleno
121      Pleno
156     Júnior
         ...
4001       NaN
4043       NaN
4048       NaN
4061       NaN
4215    Sênior
Name: NIVEL, Length: 68, dtype: object

In [93]:
media_geral = dados['IDADE'].mean() # define a variável media_geral
media_geral

np.float64(31.153517220250375)

In [94]:
dados.loc[(dados['FAIXA IDADE']=='55+') & (dados['IDADE'].isnull()), 'IDADE'] # localiza as linhas que tem a coluna FAIXA IDADE com valor 55+ e que tem a coluna IDADE como null

9      NaN
66     NaN
96     NaN
121    NaN
156    NaN
        ..
4001   NaN
4043   NaN
4048   NaN
4061   NaN
4215   NaN
Name: IDADE, Length: 68, dtype: float64

In [99]:
dados.loc[(dados['FAIXA IDADE']=='55+') & (dados['IDADE'].isnull()), 'IDADE'] = media_geral # substitui os valores null da coluna FAIXA IDADE pela variavel media_geral (31.15)

In [102]:
dados[dados['IDADE'].isnull()]['FAIXA IDADE'].value_counts() # conta quantos valores null tem preenchidos na coluna IDADE comprova que não tem mais nenhum null na faixa 55+

Series([], Name: count, dtype: int64)

### Tratando coluna salário

In [109]:
dados[dados['SALARIO'].isnull()].value_counts() # conta quantos valores null tem preenchidos na coluna SALARIO

Series([], Name: count, dtype: int64)

In [108]:
dados[dados['SALARIO'].isnull()]['FAIXA SALARIAL'].value_counts() # conta quantos valores null tem preenchidos na coluna SALARIO e compara com a coluna FAIXA SALARIAL

Series([], Name: count, dtype: int64)

In [117]:
dados.loc[dados['SALARIO'].isnull(), 'SALARIO'] # conta quantos valores null tem preenchidos na coluna SALARIO

12     NaN
28     NaN
34     NaN
39     NaN
63     NaN
        ..
4242   NaN
4252   NaN
4258   NaN
4260   NaN
4261   NaN
Name: SALARIO, Length: 577, dtype: float64

In [110]:
dados['SALARIO'].median() # calcula o valor da mediana (no caso de análise salarial, o ideal é usar a mediana pois podem haver discrepâncias de valores e a média pode não refletir a realidade por isso)

7625.5

In [121]:
mediana_salario = dados['SALARIO'].median() # define a variável mediana_salario
mediana_salario

7625.5

In [122]:
dados.loc[dados['SALARIO'].isnull(), 'SALARIO'] = mediana_salario # substitui os valores null da coluna SALARIO pela variavel mediana_salario (7625.5)

In [123]:
dados.loc[dados['SALARIO'].isnull(), 'SALARIO'] # conta quantos valores null tem preenchidos na coluna SALARIO e comprova que foram substituidos pela variavel mediana_salario (7625.5)

Series([], Name: SALARIO, dtype: float64)